[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000239086DA750>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f1b18bb4a45b9063b1b768f2915ece54
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023907B1D970>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f1b18bb4a45b9063b1b768f2915ece54
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000239086D8CB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/f1b18bb4a45b9063b1b768f2915ece54